### ISSUE TITLE
Transfer Repo to Organization and Update References

### ISSUE THREAD

**Issue by brandoningli** [jwMaxwell/Spike-2#73]
**Tasks to Complete**

- [ ] Transfer this repo to the new `spike-2` organization
- [ ] Update all references to the repo in code to either the new repo or new site as appropriate
  - [ ] `package.json`
  - [ ] `.github/workflows/auto_assign_issues.yml`
  - [ ] `.github/workflows/auto_assign_prs.yml`
  - [ ] `src/plugins/core/main.js`
- [ ] Update the remote URL in your local clone(s)
